### ISSUE TITLE
Animation can't be work, what is the issue in CI project

### ISSUE THREAD

**Issue by Pankaj-vasava** [mouse0270/bootstrap-notify#139]
I am working on CI project, i have used jquery and bootstrap-notify, there is notify plugin work well but there is problem with animation. any animation can not work, so tell me if about the issue.

**Comment by mouse0270** [comment]
Are you including the [animate.css library](http://daneden.github.io/animate.css/) or writing your own css animations?

**Comment by Pankaj-vasava** [comment]
No i am not using animation.css library, i used default animation that are included in bootsrap-notify.

**Comment by mouse0270** [comment]
I need to find a better way to make this understand.

Currently Bootstrap Notify does not include any custom css to make it as small as possible for packaging. For custom layouts and animations it relies on other libraries. For example, since bootstrap notify uses css animations instead of jQuery ones it relies on animations provided in css. This plugin does not come with any such animations packaged. I recommend that people use the "Animate.css" library (Links can be found on Bootstrap Notify website.) You can either use his full library, a portion of it, or write your own css animations.

I am sorry for the confusion this has caused, you are not the first person to interpret the documentation like this, and surely not the last. I need to find a more noticeable way to make this information clear.
