### ISSUE TITLE
[ASK] how to make auto hide off?

### ISSUE THREAD

**Issue by Dwiga** [mouse0270/bootstrap-notify#151]
I just want to make a notify that not automatically dissapeard,
how to make it, because it's doesn't explained on documentation.. 
thanks

**Comment by mouse0270** [comment]
It is in the documentation but might not be very clear due to my wording. 

_delay: if delay is set higher than 0 then the notification will auto-close after the delay period is up. Please keep in mind that delay uses milliseconds so 5000 is 5 seconds._

Meaning if you set the delay to 0, the notification will not close until the user closes it.

**Comment by Dwiga** [comment]
@mouse0270 thank you... so I've to change the delay time to 0.. I got it...

**Comment by flightsurvey** [comment]
I was looking for this too but the website with the documentation (http://bootstrap-notify.remabledesigns.com/#documentation) is just displaying a holding page.

**Comment by mouse0270** [comment]
Whoops switched servers forgot to report this url. It'll be back up today.
