### ISSUE TITLE
lost transition animations

### ISSUE THREAD

**Issue by JayAtCornwallCollege** [mouse0270/bootstrap-notify#82]
Hi, I just got the min.js file and I get notification but without the animations.  Do I need to bring in a dependency?

**Comment by mouse0270** [comment]
Yes, my plugin relies on custom css for its intro and exit animations. For this I recommend using this wonderful resource called [Animate.css](http://daneden.github.io/animate.css/) by Daniel Eden. He has put together a wonderful set of css animations that work perfectly with this plugin.

This isn't listed as a dependency because it isn't technically required. You could always write your own css animations or use a different library for the fact.

**Comment by mouse0270** [comment]
I am going to assume this was solved. If it wasn't please feel free to comment on here and I'll re-open it.

Thank you for the support.
