### ISSUE TITLE
Add class "alert-dismissible" if "allow_dismiss: true"

### ISSUE THREAD

**Issue by subsecond** [mouse0270/bootstrap-notify#83]
According to the bootstrap specs, an alert div that is dismissible needs to have class "alert-dismissible" set. Why? Because this will fix the position of the dismiss button within said div.

Here is the official spec: http://getbootstrap.com/components/#alerts-dismissible

Keep up the good work!

**Comment by mouse0270** [comment]
This is because bootstrap uses the class "alert-dismissable" to add 35px of padding to the right side of an alert then position the close button. I avoided this by using absolute position of the close button.

The absolute positioning of the close button is also their because if you add a url to the notification and are using bootstraps default styling the anchor tag would be above the close button preventing anyone from clicking on it.

Since I am not using bootstrap to dismiss an alert and am instead writing my own code for dismissing a notification I can avoid their code triggering their [alerts JavaScript plugin](http://getbootstrap.com/javascript/#alerts)

If I was to switch using the bootstrap method for dismissing alerts I wouldn't be able to provide support for making a notification into a link by passing it a url. 

I hope this explains why my plugin in works the way it does and why it doesn't use "alert-dismissible".

Thank you for your support.
